use std::fs::File;
use std::io::Read;

pub struct Book<'a> {
    path: &'a str,
    contents: Vec<u8>,
    new_words: &'a mut Vec<Vec<u8>>,
    known_words: Vec<String>,
    current_pos: usize,
}

impl<'a> Book<'a> {
    pub fn new(path: &'a str, new_words: &'a mut Vec<Vec<u8>>) -> Self {
        let contents = Vec::new();
        let current_pos = 0;
        KnownWords::new();
        let known_words = KnownWords::get_known_words();
        Self {
            path,
            contents,
            new_words,
            current_pos,
            known_words,
        }
    }


    fn open_file(&mut self) -> Result<usize, std::io::Error> {
        let file = File::open(self.path).expect("Error: File couldn't be open");
        let mut buffer = std::io::BufReader::new(file);
        let no_bytes = buffer.read_to_end(&mut self.contents)?;

        Ok(no_bytes)
    }


    pub fn get_words(&mut self) {
        let _ = self.open_file();
        while !self.is_at_end() {
            let word = self.get_word().to_ascii_lowercase();
            if Self::is_word(&word) && self.is_new_word(&word) && self.is_word_exist(&word) {
                self.new_words.push(word);
            }
        }
    }


    fn is_word_exist(&self, word: &Vec<u8>) -> bool {
        if self.new_words.contains(word) {
            false
        } else {
            true
        }
    }


    fn get_word(&mut self) -> Vec<u8> {
        let mut buffer = Vec::new();
        for index in self.current_pos..self.contents.len() {
            if self.peek(index) == b" "[0] {
                self.current_pos += 1;
                return buffer;
            } else if Self::is_punctuation(self.peek(index)) {
                self.current_pos += 1;
                return buffer;
            } else if self.is_at_end() {
                self.current_pos += 1;
                return buffer;
            } else if self.is_escape_sq() {
                self.current_pos += 1;
            } else if self.peek(index).is_ascii_digit() {
                self.current_pos += 1;
            } 
            else {
                buffer.push(self.peek(index));
                self.current_pos += 1;
            }
        }
        return buffer;
    }


    fn is_at_end(&self) -> bool {
        if self.current_pos >= self.contents.len() {
            return true;
        }
        return false;
    }


    fn is_punctuation(chars: u8) -> bool {
        match chars.to_ascii_lowercase() {
            b'.' => true,
            b',' => true,
            b'?' => true,
            b'!' => true,
            b':' => true,
            b';' => true,
            b'-' => true,
            b'(' => true,
            b')' => true,
            b'"' => true,
            _ => false,
        }
    }


    fn peek(&self, index: usize) -> u8 {
        self.contents[index]
    }


    fn is_word(word: &Vec<u8>) -> bool {
        if word.len() >= 1 && word.len() <= 3 {
            return false;
        }
        return true;
    }


    fn is_new_word(&self, word: &Vec<u8>) -> bool {
        if self
            .known_words
            .contains(&std::str::from_utf8(word).unwrap().to_string())
        {
            false
        } else {
            true
        }
    }


    fn is_escape_sq(&self) -> bool {
        match self.contents[self.current_pos] {
            b'\n' => true,
            b'\t' => true,
            b'\r' => true,
            b'\\' => true,
            b'\"' => true,
            b'\'' => true,
            b'\0' => true,
            _ => false,
        }
    }
}

struct KnownWords {}

impl KnownWords {
    fn new() -> Self {
        Self::get_known_words();
        Self {}
    }


    fn get_known_words() -> Vec<String> {
        let known_word: Vec<String> = vec![
            "ability".to_string(),
            "able".to_string(),
            "about".to_string(),
            "above".to_string(),
            "accept".to_string(),
            "according".to_string(),
            "account".to_string(),
            "across".to_string(),
            "action".to_string(),
            "activity".to_string(),
            "actually".to_string(),
            "address".to_string(),
            "administration".to_string(),
            "admit".to_string(),
            "adult".to_string(),
            "affect".to_string(),
            "after".to_string(),
            "again".to_string(),
            "against".to_string(),
            "agency".to_string(),
            "agent".to_string(),
            "agree".to_string(),
            "agreement".to_string(),
            "ahead".to_string(),
            "allow".to_string(),
            "almost".to_string(),
            "alone".to_string(),
            "along".to_string(),
            "already".to_string(),
            "also".to_string(),
            "although".to_string(),
            "always".to_string(),
            "American".to_string(),
            "among".to_string(),
            "amount".to_string(),
            "analysis".to_string(),
            "animal".to_string(),
            "another".to_string(),
            "answer".to_string(),
            "anyone".to_string(),
            "anything".to_string(),
            "appear".to_string(),
            "apply".to_string(),
            "approach".to_string(),
            "area".to_string(),
            "argue".to_string(),
            "around".to_string(),
            "arrive".to_string(),
            "article".to_string(),
            "artist".to_string(),
            "assume".to_string(),
            "attack".to_string(),
            "attention".to_string(),
            "attorney".to_string(),
            "audience".to_string(),
            "author".to_string(),
            "authority".to_string(),
            "available".to_string(),
            "avoid".to_string(),
            "away".to_string(),
            "baby".to_string(),
            "back".to_string(),
            "ball".to_string(),
            "bank".to_string(),
            "base".to_string(),
            "beat".to_string(),
            "beautiful".to_string(),
            "because".to_string(),
            "become".to_string(),
            "before".to_string(),
            "begin".to_string(),
            "behavior".to_string(),
            "behind".to_string(),
            "believe".to_string(),
            "benefit".to_string(),
            "best".to_string(),
            "better".to_string(),
            "between".to_string(),
            "beyond".to_string(),
            "bill".to_string(),
            "billion".to_string(),
            "black".to_string(),
            "blood".to_string(),
            "blue".to_string(),
            "board".to_string(),
            "body".to_string(),
            "book".to_string(),
            "born".to_string(),
            "both".to_string(),
            "break".to_string(),
            "bring".to_string(),
            "brother".to_string(),
            "budget".to_string(),
            "build".to_string(),
            "building".to_string(),
            "business".to_string(),
            "call".to_string(),
            "camera".to_string(),
            "campaign".to_string(),
            "cancer".to_string(),
            "candidate".to_string(),
            "capital".to_string(),
            "card".to_string(),
            "care".to_string(),
            "career".to_string(),
            "carry".to_string(),
            "case".to_string(),
            "catch".to_string(),
            "cause".to_string(),
            "cell".to_string(),
            "center".to_string(),
            "central".to_string(),
            "century".to_string(),
            "certain".to_string(),
            "certainly".to_string(),
            "chair".to_string(),
            "challenge".to_string(),
            "chance".to_string(),
            "change".to_string(),
            "character".to_string(),
            "charge".to_string(),
            "check".to_string(),
            "child".to_string(),
            "choice".to_string(),
            "choose".to_string(),
            "church".to_string(),
            "citizen".to_string(),
            "city".to_string(),
            "civil".to_string(),
            "claim".to_string(),
            "class".to_string(),
            "clear".to_string(),
            "clearly".to_string(),
            "close".to_string(),
            "coach".to_string(),
            "cold".to_string(),
            "collection".to_string(),
            "college".to_string(),
            "color".to_string(),
            "come".to_string(),
            "commercial".to_string(),
            "common".to_string(),
            "community".to_string(),
            "company".to_string(),
            "compare".to_string(),
            "computer".to_string(),
            "concern".to_string(),
            "condition".to_string(),
            "conference".to_string(),
            "Congress".to_string(),
            "consider".to_string(),
            "consumer".to_string(),
            "contain".to_string(),
            "continue".to_string(),
            "control".to_string(),
            "cost".to_string(),
            "could".to_string(),
            "country".to_string(),
            "couple".to_string(),
            "course".to_string(),
            "court".to_string(),
            "cover".to_string(),
            "create".to_string(),
            "crime".to_string(),
            "cultural".to_string(),
            "culture".to_string(),
            "current".to_string(),
            "customer".to_string(),
            "dark".to_string(),
            "data".to_string(),
            "daughter".to_string(),
            "dead".to_string(),
            "deal".to_string(),
            "death".to_string(),
            "debate".to_string(),
            "decade".to_string(),
            "decide".to_string(),
            "decision".to_string(),
            "deep".to_string(),
            "defense".to_string(),
            "degree".to_string(),
            "Democrat".to_string(),
            "democratic".to_string(),
            "describe".to_string(),
            "design".to_string(),
            "despite".to_string(),
            "detail".to_string(),
            "determine".to_string(),
            "develop".to_string(),
            "development".to_string(),
            "difference".to_string(),
            "different".to_string(),
            "difficult".to_string(),
            "dinner".to_string(),
            "direction".to_string(),
            "director".to_string(),
            "discover".to_string(),
            "discuss".to_string(),
            "discussion".to_string(),
            "disease".to_string(),
            "doctor".to_string(),
            "door".to_string(),
            "down".to_string(),
            "draw".to_string(),
            "dream".to_string(),
            "drive".to_string(),
            "drop".to_string(),
            "drug".to_string(),
            "during".to_string(),
            "each".to_string(),
            "early".to_string(),
            "east".to_string(),
            "easy".to_string(),
            "economic".to_string(),
            "economy".to_string(),
            "edge".to_string(),
            "education".to_string(),
            "effect".to_string(),
            "effort".to_string(),
            "eight".to_string(),
            "either".to_string(),
            "election".to_string(),
            "else".to_string(),
            "employee".to_string(),
            "energy".to_string(),
            "enjoy".to_string(),
            "enough".to_string(),
            "enter".to_string(),
            "entire".to_string(),
            "environment".to_string(),
            "environmental".to_string(),
            "especially".to_string(),
            "establish".to_string(),
            "even".to_string(),
            "evening".to_string(),
            "event".to_string(),
            "ever".to_string(),
            "every".to_string(),
            "everybody".to_string(),
            "everyone".to_string(),
            "everything".to_string(),
            "evidence".to_string(),
            "exactly".to_string(),
            "example".to_string(),
            "executive".to_string(),
            "exist".to_string(),
            "expect".to_string(),
            "experience".to_string(),
            "expert".to_string(),
            "explain".to_string(),
            "face".to_string(),
            "fact".to_string(),
            "factor".to_string(),
            "fail".to_string(),
            "fall".to_string(),
            "family".to_string(),
            "fast".to_string(),
            "father".to_string(),
            "fear".to_string(),
            "federal".to_string(),
            "feel".to_string(),
            "feeling".to_string(),
            "field".to_string(),
            "fight".to_string(),
            "figure".to_string(),
            "fill".to_string(),
            "film".to_string(),
            "final".to_string(),
            "finally".to_string(),
            "financial".to_string(),
            "find".to_string(),
            "fine".to_string(),
            "finger".to_string(),
            "finish".to_string(),
            "fire".to_string(),
            "firm".to_string(),
            "first".to_string(),
            "fish".to_string(),
            "five".to_string(),
            "floor".to_string(),
            "focus".to_string(),
            "follow".to_string(),
            "food".to_string(),
            "foot".to_string(),
            "force".to_string(),
            "foreign".to_string(),
            "forget".to_string(),
            "form".to_string(),
            "former".to_string(),
            "forward".to_string(),
            "four".to_string(),
            "free".to_string(),
            "friend".to_string(),
            "from".to_string(),
            "front".to_string(),
            "full".to_string(),
            "fund".to_string(),
            "future".to_string(),
            "game".to_string(),
            "garden".to_string(),
            "general".to_string(),
            "generation".to_string(),
            "girl".to_string(),
            "give".to_string(),
            "glass".to_string(),
            "goal".to_string(),
            "good".to_string(),
            "government".to_string(),
            "great".to_string(),
            "green".to_string(),
            "ground".to_string(),
            "group".to_string(),
            "grow".to_string(),
            "growth".to_string(),
            "guess".to_string(),
            "hair".to_string(),
            "half".to_string(),
            "hand".to_string(),
            "hang".to_string(),
            "happen".to_string(),
            "happy".to_string(),
            "hard".to_string(),
            "have".to_string(),
            "head".to_string(),
            "health".to_string(),
            "hear".to_string(),
            "heart".to_string(),
            "heat".to_string(),
            "heavy".to_string(),
            "help".to_string(),
            "here".to_string(),
            "herself".to_string(),
            "high".to_string(),
            "himself".to_string(),
            "history".to_string(),
            "hold".to_string(),
            "home".to_string(),
            "hope".to_string(),
            "hospital".to_string(),
            "hotel".to_string(),
            "hour".to_string(),
            "house".to_string(),
            "however".to_string(),
            "huge".to_string(),
            "human".to_string(),
            "hundred".to_string(),
            "husband".to_string(),
            "idea".to_string(),
            "identify".to_string(),
            "image".to_string(),
            "imagine".to_string(),
            "impact".to_string(),
            "important".to_string(),
            "improve".to_string(),
            "include".to_string(),
            "including".to_string(),
            "increase".to_string(),
            "indeed".to_string(),
            "indicate".to_string(),
            "individual".to_string(),
            "industry".to_string(),
            "information".to_string(),
            "inside".to_string(),
            "instead".to_string(),
            "institution".to_string(),
            "interest".to_string(),
            "interesting".to_string(),
            "international".to_string(),
            "interview".to_string(),
            "into".to_string(),
            "investment".to_string(),
            "involve".to_string(),
            "issue".to_string(),
            "item".to_string(),
            "itself".to_string(),
            "join".to_string(),
            "just".to_string(),
            "keep".to_string(),
            "kill".to_string(),
            "kind".to_string(),
            "kitchen".to_string(),
            "know".to_string(),
            "knowledge".to_string(),
            "land".to_string(),
            "language".to_string(),
            "large".to_string(),
            "last".to_string(),
            "late".to_string(),
            "later".to_string(),
            "laugh".to_string(),
            "lawyer".to_string(),
            "lead".to_string(),
            "leader".to_string(),
            "learn".to_string(),
            "least".to_string(),
            "leave".to_string(),
            "left".to_string(),
            "legal".to_string(),
            "less".to_string(),
            "letter".to_string(),
            "level".to_string(),
            "life".to_string(),
            "light".to_string(),
            "like".to_string(),
            "likely".to_string(),
            "line".to_string(),
            "list".to_string(),
            "listen".to_string(),
            "little".to_string(),
            "live".to_string(),
            "local".to_string(),
            "long".to_string(),
            "look".to_string(),
            "lose".to_string(),
            "loss".to_string(),
            "love".to_string(),
            "machine".to_string(),
            "magazine".to_string(),
            "main".to_string(),
            "maintain".to_string(),
            "major".to_string(),
            "majority".to_string(),
            "make".to_string(),
            "manage".to_string(),
            "management".to_string(),
            "manager".to_string(),
            "many".to_string(),
            "market".to_string(),
            "marriage".to_string(),
            "material".to_string(),
            "matter".to_string(),
            "maybe".to_string(),
            "mean".to_string(),
            "measure".to_string(),
            "media".to_string(),
            "medical".to_string(),
            "meet".to_string(),
            "meeting".to_string(),
            "member".to_string(),
            "memory".to_string(),
            "mention".to_string(),
            "message".to_string(),
            "method".to_string(),
            "middle".to_string(),
            "might".to_string(),
            "military".to_string(),
            "million".to_string(),
            "mind".to_string(),
            "minute".to_string(),
            "miss".to_string(),
            "mission".to_string(),
            "model".to_string(),
            "modern".to_string(),
            "moment".to_string(),
            "money".to_string(),
            "month".to_string(),
            "more".to_string(),
            "morning".to_string(),
            "most".to_string(),
            "mother".to_string(),
            "mouth".to_string(),
            "move".to_string(),
            "movement".to_string(),
            "movie".to_string(),
            "much".to_string(),
            "music".to_string(),
            "must".to_string(),
            "myself".to_string(),
            "name".to_string(),
            "nation".to_string(),
            "national".to_string(),
            "natural".to_string(),
            "nature".to_string(),
            "near".to_string(),
            "nearly".to_string(),
            "necessary".to_string(),
            "need".to_string(),
            "network".to_string(),
            "never".to_string(),
            "news".to_string(),
            "newspaper".to_string(),
            "next".to_string(),
            "nice".to_string(),
            "night".to_string(),
            "none".to_string(),
            "north".to_string(),
            "note".to_string(),
            "nothing".to_string(),
            "notice".to_string(),
            "number".to_string(),
            "occur".to_string(),
            "offer".to_string(),
            "office".to_string(),
            "officer".to_string(),
            "official".to_string(),
            "often".to_string(),
            "once".to_string(),
            "only".to_string(),
            "onto".to_string(),
            "open".to_string(),
            "operation".to_string(),
            "opportunity".to_string(),
            "option".to_string(),
            "order".to_string(),
            "organization".to_string(),
            "other".to_string(),
            "others".to_string(),
            "outside".to_string(),
            "over".to_string(),
            "owner".to_string(),
            "page".to_string(),
            "pain".to_string(),
            "painting".to_string(),
            "paper".to_string(),
            "parent".to_string(),
            "part".to_string(),
            "participant".to_string(),
            "particular".to_string(),
            "particularly".to_string(),
            "partner".to_string(),
            "party".to_string(),
            "pass".to_string(),
            "past".to_string(),
            "patient".to_string(),
            "pattern".to_string(),
            "peace".to_string(),
            "people".to_string(),
            "perform".to_string(),
            "performance".to_string(),
            "perhaps".to_string(),
            "period".to_string(),
            "person".to_string(),
            "personal".to_string(),
            "phone".to_string(),
            "physical".to_string(),
            "pick".to_string(),
            "picture".to_string(),
            "piece".to_string(),
            "place".to_string(),
            "plan".to_string(),
            "plant".to_string(),
            "play".to_string(),
            "player".to_string(),
            "point".to_string(),
            "police".to_string(),
            "policy".to_string(),
            "political".to_string(),
            "politics".to_string(),
            "poor".to_string(),
            "popular".to_string(),
            "population".to_string(),
            "position".to_string(),
            "positive".to_string(),
            "possible".to_string(),
            "power".to_string(),
            "practice".to_string(),
            "prepare".to_string(),
            "present".to_string(),
            "president".to_string(),
            "pressure".to_string(),
            "pretty".to_string(),
            "prevent".to_string(),
            "price".to_string(),
            "private".to_string(),
            "probably".to_string(),
            "problem".to_string(),
            "process".to_string(),
            "produce".to_string(),
            "product".to_string(),
            "production".to_string(),
            "professional".to_string(),
            "professor".to_string(),
            "program".to_string(),
            "project".to_string(),
            "property".to_string(),
            "protect".to_string(),
            "prove".to_string(),
            "provide".to_string(),
            "public".to_string(),
            "pull".to_string(),
            "purpose".to_string(),
            "push".to_string(),
            "quality".to_string(),
            "question".to_string(),
            "quickly".to_string(),
            "quite".to_string(),
            "race".to_string(),
            "radio".to_string(),
            "raise".to_string(),
            "range".to_string(),
            "rate".to_string(),
            "rather".to_string(),
            "reach".to_string(),
            "read".to_string(),
            "ready".to_string(),
            "real".to_string(),
            "reality".to_string(),
            "realize".to_string(),
            "really".to_string(),
            "reason".to_string(),
            "receive".to_string(),
            "recent".to_string(),
            "recently".to_string(),
            "recognize".to_string(),
            "record".to_string(),
            "reduce".to_string(),
            "reflect".to_string(),
            "region".to_string(),
            "relate".to_string(),
            "relationship".to_string(),
            "religious".to_string(),
            "remain".to_string(),
            "remember".to_string(),
            "remove".to_string(),
            "report".to_string(),
            "represent".to_string(),
            "Republican".to_string(),
            "require".to_string(),
            "research".to_string(),
            "resource".to_string(),
            "respond".to_string(),
            "response".to_string(),
            "responsibility".to_string(),
            "rest".to_string(),
            "result".to_string(),
            "return".to_string(),
            "reveal".to_string(),
            "rich".to_string(),
            "right".to_string(),
            "rise".to_string(),
            "risk".to_string(),
            "road".to_string(),
            "rock".to_string(),
            "role".to_string(),
            "room".to_string(),
            "rule".to_string(),
            "safe".to_string(),
            "same".to_string(),
            "save".to_string(),
            "scene".to_string(),
            "school".to_string(),
            "science".to_string(),
            "scientist".to_string(),
            "score".to_string(),
            "season".to_string(),
            "seat".to_string(),
            "second".to_string(),
            "section".to_string(),
            "security".to_string(),
            "seek".to_string(),
            "seem".to_string(),
            "sell".to_string(),
            "send".to_string(),
            "senior".to_string(),
            "sense".to_string(),
            "series".to_string(),
            "serious".to_string(),
            "serve".to_string(),
            "service".to_string(),
            "seven".to_string(),
            "several".to_string(),
            "sexual".to_string(),
            "shake".to_string(),
            "share".to_string(),
            "shoot".to_string(),
            "short".to_string(),
            "shot".to_string(),
            "should".to_string(),
            "shoulder".to_string(),
            "show".to_string(),
            "side".to_string(),
            "sign".to_string(),
            "significant".to_string(),
            "similar".to_string(),
            "simple".to_string(),
            "simply".to_string(),
            "since".to_string(),
            "sing".to_string(),
            "single".to_string(),
            "sister".to_string(),
            "site".to_string(),
            "situation".to_string(),
            "size".to_string(),
            "skill".to_string(),
            "skin".to_string(),
            "small".to_string(),
            "smile".to_string(),
            "social".to_string(),
            "society".to_string(),
            "soldier".to_string(),
            "some".to_string(),
            "somebody".to_string(),
            "someone".to_string(),
            "something".to_string(),
            "sometimes".to_string(),
            "song".to_string(),
            "soon".to_string(),
            "sort".to_string(),
            "sound".to_string(),
            "source".to_string(),
            "south".to_string(),
            "southern".to_string(),
            "space".to_string(),
            "speak".to_string(),
            "special".to_string(),
            "specific".to_string(),
            "speech".to_string(),
            "spend".to_string(),
            "sport".to_string(),
            "spring".to_string(),
            "staff".to_string(),
            "stage".to_string(),
            "stand".to_string(),
            "standard".to_string(),
            "star".to_string(),
            "start".to_string(),
            "state".to_string(),
            "statement".to_string(),
            "station".to_string(),
            "stay".to_string(),
            "step".to_string(),
            "still".to_string(),
            "stock".to_string(),
            "stop".to_string(),
            "store".to_string(),
            "story".to_string(),
            "strategy".to_string(),
            "street".to_string(),
            "strong".to_string(),
            "structure".to_string(),
            "student".to_string(),
            "study".to_string(),
            "stuff".to_string(),
            "style".to_string(),
            "subject".to_string(),
            "success".to_string(),
            "successful".to_string(),
            "such".to_string(),
            "suddenly".to_string(),
            "suffer".to_string(),
            "suggest".to_string(),
            "summer".to_string(),
            "support".to_string(),
            "sure".to_string(),
            "surface".to_string(),
            "system".to_string(),
            "table".to_string(),
            "take".to_string(),
            "talk".to_string(),
            "task".to_string(),
            "teach".to_string(),
            "teacher".to_string(),
            "team".to_string(),
            "technology".to_string(),
            "television".to_string(),
            "tell".to_string(),
            "tend".to_string(),
            "term".to_string(),
            "test".to_string(),
            "than".to_string(),
            "thank".to_string(),
            "that".to_string(),
            "their".to_string(),
            "them".to_string(),
            "themselves".to_string(),
            "then".to_string(),
            "theory".to_string(),
            "there".to_string(),
            "these".to_string(),
            "they".to_string(),
            "thing".to_string(),
            "think".to_string(),
            "third".to_string(),
            "this".to_string(),
            "those".to_string(),
            "though".to_string(),
            "thought".to_string(),
            "thousand".to_string(),
            "threat".to_string(),
            "three".to_string(),
            "through".to_string(),
            "throughout".to_string(),
            "throw".to_string(),
            "thus".to_string(),
            "time".to_string(),
            "today".to_string(),
            "together".to_string(),
            "tonight".to_string(),
            "total".to_string(),
            "tough".to_string(),
            "toward".to_string(),
            "town".to_string(),
            "trade".to_string(),
            "traditional".to_string(),
            "training".to_string(),
            "travel".to_string(),
            "treat".to_string(),
            "treatment".to_string(),
            "tree".to_string(),
            "trial".to_string(),
            "trip".to_string(),
            "trouble".to_string(),
            "true".to_string(),
            "truth".to_string(),
            "turn".to_string(),
            "type".to_string(),
            "under".to_string(),
            "understand".to_string(),
            "unit".to_string(),
            "until".to_string(),
            "upon".to_string(),
            "usually".to_string(),
            "value".to_string(),
            "various".to_string(),
            "very".to_string(),
            "victim".to_string(),
            "view".to_string(),
            "violence".to_string(),
            "visit".to_string(),
            "voice".to_string(),
            "vote".to_string(),
            "wait".to_string(),
            "walk".to_string(),
            "wall".to_string(),
            "want".to_string(),
            "watch".to_string(),
            "water".to_string(),
            "weapon".to_string(),
            "wear".to_string(),
            "week".to_string(),
            "weight".to_string(),
            "well".to_string(),
            "west".to_string(),
            "western".to_string(),
            "what".to_string(),
            "whatever".to_string(),
            "when".to_string(),
            "where".to_string(),
            "whether".to_string(),
            "which".to_string(),
            "while".to_string(),
            "white".to_string(),
            "whole".to_string(),
            "whom".to_string(),
            "whose".to_string(),
            "wide".to_string(),
            "wife".to_string(),
            "will".to_string(),
            "wind".to_string(),
            "window".to_string(),
            "wish".to_string(),
            "with".to_string(),
            "within".to_string(),
            "without".to_string(),
            "woman".to_string(),
            "wonder".to_string(),
            "word".to_string(),
            "work".to_string(),
            "worker".to_string(),
            "world".to_string(),
            "worry".to_string(),
            "would".to_string(),
            "write".to_string(),
            "writer".to_string(),
            "wrong".to_string(),
            "yard".to_string(),
            "yeah".to_string(),
            "year".to_string(),
            "young".to_string(),
            "your".to_string(),
            "yourself".to_string(),
        ];

        known_word
    }
}
